name: Change Log
on: [push]
jobs:
  build:
    name: changeLog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: locator
        run: pwd
      - name: run
        run: sh ./scripts/log.sh