name: Change Log
on: [push]
jobs:
  build:
    name: changeLog
    runs-on: ubuntu-latest
    steps:
      - name: locator
        run: pwd
      - name: mayI
        run: ls -l ./scripts
      - name: run
        run: ./scripts/log.sh